import { Header } from "@/components/Header";
import "./globals.css";
import { Inter, Space_Grotesk, Roboto } from "next/font/google";
import { HeroCarousel } from "@/components/HeroCarousel";
import React from "react";
import Providers from "@/redux/Provider";
import { Footer } from "@/components/Footer";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
export const metadata = {
  title: "next-store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-main  ${spaceGrotesk.className}`}>
        <Providers>
          <header className="shadow-md bg-opacity-60 bg-white h-[55px]">
            <Header />
          </header>
          <HeroCarousel />

          <main className="max-w-10xl mx-auto bg-main  ">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
